### ISSUE TITLE
Since updating to 0.5.2, Arc does not open automatically based on rules in config.json

### ISSUE THREAD

**Issue by jonnyborbs** [Browsers-software/browsers#139]
**Describe the bug**
This was working before in 0.5.1 with the profile support removed per advice in https://github.com/Browsers-software/browsers/issues/94#issuecomment-1923228107 

Now, my configured links that should direct to Arc bring up the app selection pop-up. Selecting Arc does work. But they aren't automatically being routed there.

An example rule:

```
    {
      "source_app": null,
      "url_pattern": "*://docs.google.com/**",
      "opener": null,
      "profile": "/Applications/Arc.app/Contents/MacOS/Arc#Default",
      "incognito": false
    },

```

**System:**
 - OS: Sonoma 14.3.1
 - Browsers Version 0.5.2

**Comment by jonnyborbs** [comment]
I figured this out by using the GUI rule editor to update a single rule and checking the diff between it and my old ones:

The `profile_order` stanza needed to be updated to remove the `#Default` suffix on the Arc line item

And each individual rule needed its `profile` updated to change from `.../MacOS/Arc/#Default` to `.../MacOS/Arc/#`

**Comment by liias** [comment]
Indeed, the profile changed to `/Applications/Arc.app/Contents/MacOS/Arc`, because profile support was removed for Arc.

Btw, also the `profile` is not deprecated and `opener` is used instead. This, and some upcoming versions of Browsers will still support `profile`, and automatically update it to `opener` if you edit any Rule via Settings UI.
