### ISSUE TITLE
Firefox containers are not working

### ISSUE THREAD

**Issue by codemedic** [Browsers-software/browsers#16]
**Describe the bug**
The pop-up does not show my Firefox containers, despite installing the suggested extension.

**To Reproduce**
1. Install firefox
2. Install `Firefox Multi-Account Containers` addon
3. Install `Open external links in a container` addon
4. Create a couple of containers, or use the defaults

**Expected behavior**
When clicking on a URL I would expect to see firefox containers listed there.

**Screenshots**
N/A

**Desktop (please complete the following information):**
 - OS: KDE Neon 22.04
 - Browser: Firefox
 - Version: 111.0.1

**Smartphone (please complete the following information):**
 - N/A

**Additional context**
N/A

**Comment by liias** [comment]
Did you refresh the list of browsers? Using the `⋮` menu.

**Comment by codemedic** [comment]
Yes, I tried refresh and scroll. Only one entry for Firefox is shown. No container specific one.

**Comment by liias** [comment]
Could you refresh the list again and then see recent logs.
Check if logs has any lines starting with `Skipping containers for profile` and please post the ending of those lines here.

I'm going to try it out in Linux in a few weeks to take a closer look.

**Comment by liias** [comment]
Hey, @GRbit Could you specify (1) which linux distro you use, (2) which desktop environment you use, (3) which packaging you used to install firefox and (4) does Firefox show up in you system settings where you can choose a default browser.

Could you also check log file to see if there is anything mentioned about Firefox.

About your second question, no there is no builtin way to add custom entries in settings, I really really want to get it working in a way, where it "just works".

**Comment by GRbit** [comment]
@liias Thank you very much for the prompt response!

1. Debian based MX-Linux
2. XFCE
3. firefox (`sudo apt install firefox`)
4. It does, but I'm not sure if it was by default. My configs lived for years, so I may did something for it to be shown there. For some reason I remember that there were some problems with Firefox checking that it's a default browser and asking me to choose it as default over and over.

> Could you also check log file to see if there is anything mentioned about Firefox.

Nothing
```
INFO browsers: Starting Browsers
INFO browsers: Logging to /home/grbit/.local/state/software.Browsers/logs/browsers.log
INFO browsers::utils: Config: /home/grbit/.local/share/software.Browsers/config.json
INFO druid_shell::backend::gtk::application: gtk: Activated application
```

I awe your goal, it's really inspiring and amazing to see people in Linux community who set the bar this high. Can only wish you a lot of luck, since Linux distros is peculiar zoo with tons of rare species. Though, I might be a good thing to have at least an option of using some widespread standards like `*desktop` files for example. I know firefox doesn't create this one, but for other software like `browsers` I've created some for firefox profiles and it worked.

Also, if you can share some articles or docs describing the way you are detecting Firefox profiles, I'll spent some time to check if it's possible in my system to detect profiles in a similar way. I mean, maybe it's just another directory or something like this. I'm not good at reading rust code, but don't be afraid of sharing some technical details.

**Comment by codemedic** [comment]
```
2023-04-19T01:21:03.574087784+01:00  INFO browsers: refresh called
2023-04-19T01:21:03.574087784+01:00  INFO browsers: refresh called
icon: /usr/share/icons/hicolor/48x48/apps/firefox.png
icon: /usr/share/icons/hicolor/48x48/apps/google-chrome.png
icon: /usr/share/icons/hicolor/48x48/apps/opera.png
2023-04-19T01:21:03.853545666+01:00  INFO browsers::utils: Config: /home/dk/.local/share/software.Browsers/config.json
2023-04-19T01:21:03.853545666+01:00  INFO browsers::utils: Config: /home/dk/.local/share/software.Browsers/config.json

```
No mention of any errors related to firefox in the logs.

PS: Sorry for the late reply; been away.

**Comment by GRbit** [comment]
Just in case it could be needed too, here is my log 
```
2023-04-19T11:40:25.547566411+02:00  INFO browsers: refresh called
icon: /home/grbit/.local/share/icons/telegram.png
icon: /home/grbit/.local/share/icons/telegram.png
icon: /usr/share/pixmaps/Zoom.png
icon: /usr/share/icons/hicolor/48x48/apps/org.xfce.webbrowser.png
icon: /usr/share/pixmaps/firefox.png
icon: /usr/share/pixmaps/firefox.png
icon: /usr/share/icons/hicolor/48x48/apps/chromium.png
icon: /usr/share/icons/hicolor/48x48/apps/google-chrome.png
icon: /usr/share/icons/hicolor/64x64/apps/librewolf.png
2023-04-19T11:40:26.142869845+02:00  INFO browsers::utils: Config: /home/grbit/.local/share/software.Browsers/config.json
```

**Comment by liias** [comment]
@GRbit I moved your issue to a new issue #20. It seems a bit more complicated problem, but I will need to dig deeper into your specific distro/xfce.

---

@codemedic, I will also look this week into issue with firefox containers, but I think the fix is rather easy.
Your probably also don't see a firefox profile name under Firefox title?

Browsers is detecting browsers by their `.desktop` file name. Could you see what's the one in KDE neon?
E.g `locate firefox.desktop`

**Comment by GRbit** [comment]
@liias 
```
Browsers is detecting browsers by their .desktop file name
```
I've added `*.desktop` files after I've installed `browsers`, and it didn't detected it even after I've hit refresh button. BUT after reboot it finally found these files I've created. At the same time, it still didn't found the original files. I will post files content in https://github.com/Browsers-software/browsers/issues/20

Also, another software I tried https://github.com/properlypurple/braus also doesn't detect original firefox.desktop file, but detects files that I've created myself. So, I guess it might be something wrong with the original desktop file.

**Comment by liias** [comment]
Hey, @codemedic, this issue should be fixed. Please download the latest version and refresh the list.
I will close the issue, feel free to re-open if the issue still exists.

@GRbit , thanks for testing, let's continue that discussion in issue #20 then.

**Comment by codemedic** [comment]
@liias even though this didn't fix the issue for my setup, I recently noticed that the profile opened by Browsers is called `default` while my default profile was called `default-release`. It is apparently the profile name used since v67 of firefox. https://superuser.com/a/1556315/28775

So, I tried deleting the `default` profile created by Browsers and that fixed the problem.
